web:
    build: .
    command: celery  -B -A Book-book worker -l info
    volumes:
        - .:/Book-book
    links:
        - redis
    container_name: book

redis:
    image: redis
    container_name: database