version: '3'
services:
  app:
      build: .
      command: celery  -B -A Book-book worker -l info
      volumes:
          - .:/Book-book
      links:
          - redis
      container_name: book
      depends_on:
        - redis

  redis:
      image: "redis:alpine"
      container_name: database