name: "Github Action Send Email"

on:
  push:
    branches:
      - master
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 'run scripts'
        run: 'python -m main'
        env:
          MailUser: ${{secrets.MailUser}}
          MailPass: ${{secrets.MailPass}}
